### ISSUE TITLE
[spoiler] not working

### ISSUE THREAD

**Issue by Firew0lf** [TamiaLab/PySkCode#1]
Code de test:
```
[b]Bold[/b]
[i]Italic[/i]
[u]underline[/u]
[s]strike[/s]
[color=red]R[color=green]G[color=blue]B[/color]
[color=orange][b][i][u][s]Everything ![/s][/u][/i][/b][/color]
[quote="Intel"]Pentium[/quote]
[list]TODO:
[li]Ranger mes chaussettes[/li]
[li]Chaussettes mes ranger[/li]
[/list]
H[sub]2[/sub]O[sup]-[/sup]
[spoiler][glow]Yé souis caché[/glow][/spoiler]
```

Résultat: Pas de spoiler pour "Yé souis caché", mais le [glow] fonctionne bien. Même problème sans autre balise: `[spoiler]Yé souis caché[/spoiler]. Pas d'erreur "balises rouges" ou "balises juste affichées sans parser" non plus. Cependant, la balise fonctionne en texte brut.

Navigateur: Firefox 42.0, Windows 8 64bits (mais ça osef)

**Comment by skywodd** [comment]
Oups. J'ai oublié le morceau de CSS pour le spoiler (de même que pour ispoiler).
Je vais regarder ça demain matin. C'est une erreur d'interface chaise-clavier.

Merci pour le ticket de bug :)

**Comment by skywodd** [comment]
C'est corrigé, encore merci :)
